import logging
from typing import List, Dict, Any

from qdrant_client import QdrantClient, models
from qdrant_client.models import Distance, VectorParams, PointStruct, SparseVector
from fastembed import SparseTextEmbedding
import numpy as np

logger = logging.getLogger(__name__)

SPARSE_VECTOR_NAME = "sparse-text"


class HybridRetriever:
    """
    Hybrid retriever combining Dense vector search and Sparse (BM25-like) search
    natively on Qdrant using Prefetch + RRF Fusion.

    Sparse embeddings are generated by fastembed (SPLADE model) and stored
    directly inside Qdrant alongside dense embeddings. No in-memory BM25 index
    is needed — everything is persisted and queried server-side.
    """

    def __init__(
        self,
        qdrant_client: QdrantClient,
        collection_name: str,
        embedding_service,
        alpha: float = 0.5,
    ):
        """
        Initialize hybrid retriever

        Args:
            qdrant_client: Qdrant client instance
            collection_name: Name of the collection
            embedding_service: Dense embedding service instance
            alpha: (kept for interface compatibility, RRF fusion replaces alpha blending)
        """
        self.client = qdrant_client
        self.collection_name = collection_name
        self.embedding_service = embedding_service
        self.alpha = alpha

        self.sparse_model = SparseTextEmbedding(
            model_name="Qdrant/bm25",
        )
        logger.info("Sparse embedding model (Qdrant/bm25) loaded for fastembed")

    def create_collection(self, vector_size: int):
        """
        Create Qdrant collection with both dense and sparse vector configs.
        If the collection already exists it will be recreated (data will be lost).
        """
        try:
            self.client.recreate_collection(
                collection_name=self.collection_name,
                vectors_config=VectorParams(
                    size=vector_size,
                    distance=Distance.COSINE,
                ),
                sparse_vectors_config={
                    SPARSE_VECTOR_NAME: models.SparseVectorParams(
                        modifier=models.Modifier.IDF,
                    )
                },
            )
            logger.info(
                f"Collection '{self.collection_name}' created with dense + sparse vector config"
            )
            return True
        except Exception as e:
            logger.error(f"Failed to create collection: {str(e)}")
            return False

    def index_documents(self, documents: List[Dict[str, Any]]):
        """
        Index documents into Qdrant with both dense and sparse embeddings.

        Args:
            documents: List of documents with 'id', 'question', 'answer', 'context'
        """
        logger.info(f"Indexing {len(documents)} documents...")

        texts = []
        doc_ids = []

        for doc in documents:
            text = f"{doc.get('question', '')} {doc.get('answer', '')} {doc.get('context', '')}".strip()
            texts.append(text)
            doc_ids.append(doc.get("id", str(len(doc_ids))))

        logger.info("Generating dense embeddings...")
        dense_embeddings = self.embedding_service.encode_documents(texts)

        logger.info("Generating sparse embeddings via fastembed...")
        sparse_embeddings = list(self.sparse_model.embed(texts))

        logger.info("Uploading points to Qdrant (dense + sparse)...")
        batch_size = 100
        for batch_start in range(0, len(documents), batch_size):
            batch_end = min(batch_start + batch_size, len(documents))
            points = []

            for idx in range(batch_start, batch_end):
                doc = documents[idx]
                dense_vec = dense_embeddings[idx].tolist()
                sp = sparse_embeddings[idx]

                point = PointStruct(
                    id=idx,
                    vector={
                        "": dense_vec,
                        SPARSE_VECTOR_NAME: SparseVector(
                            indices=sp.indices.tolist(),
                            values=sp.values.tolist(),
                        ),
                    },
                    payload={
                        "doc_id": doc_ids[idx],
                        "question": doc.get("question", ""),
                        "answer": doc.get("answer", ""),
                        "context": doc.get("context", ""),
                        "text": texts[idx],
                    },
                )
                points.append(point)

            self.client.upsert(
                collection_name=self.collection_name,
                points=points,
            )
            logger.info(f"  Uploaded batch {batch_start}-{batch_end}")

        logger.info(f"Indexed {len(documents)} documents (dense + sparse) into Qdrant")

    def hybrid_search(self, query: str, top_k: int = 30) -> List[Dict]:
        """
        Perform hybrid search using Qdrant Prefetch + RRF Fusion.

        Dense and sparse sub-queries are sent to Qdrant in a single request.
        Qdrant fuses results using Reciprocal Rank Fusion (RRF) server-side,
        eliminating the need for manual score normalization in Python.

        Args:
            query: Search query
            top_k: Number of results to return

        Returns:
            List of documents with combined scores
        """
        dense_query_vector = self.embedding_service.encode_query(query).tolist()

        sparse_query_list = list(self.sparse_model.embed([query]))
        sq = sparse_query_list[0]

        prefetch_limit = max(top_k * 3, 50)

        response = self.client.query_points(
            collection_name=self.collection_name,
            prefetch=[
                models.Prefetch(
                    query=dense_query_vector,
                    using="",
                    limit=prefetch_limit,
                ),
                models.Prefetch(
                    query=models.SparseVector(
                        indices=sq.indices.tolist(),
                        values=sq.values.tolist(),
                    ),
                    using=SPARSE_VECTOR_NAME,
                    limit=prefetch_limit,
                ),
            ],
            query=models.FusionQuery(
                fusion=models.Fusion.RRF,
            ),
            limit=top_k,
            with_payload=True,
        )

        results = []
        for point in response.points:
            payload = point.payload or {}
            results.append(
                {
                    "doc_id": payload.get("doc_id", ""),
                    "question": payload.get("question", ""),
                    "answer": payload.get("answer", ""),
                    "context": payload.get("context", ""),
                    "text": payload.get("text", ""),
                    "score": point.score,
                }
            )

        return results
